package com.codejoys.company.mapper;

import com.codejoys.company.entity.CurrentDeptEmp;
import com.codejoys.company.entity.CurrentDeptEmpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CurrentDeptEmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table current_dept_emp
     *
     * @mbg.generated
     */
    long countByExample(CurrentDeptEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table current_dept_emp
     *
     * @mbg.generated
     */
    int deleteByExample(CurrentDeptEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table current_dept_emp
     *
     * @mbg.generated
     */
    int insert(CurrentDeptEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table current_dept_emp
     *
     * @mbg.generated
     */
    int insertSelective(CurrentDeptEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table current_dept_emp
     *
     * @mbg.generated
     */
    List<CurrentDeptEmp> selectByExample(CurrentDeptEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table current_dept_emp
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CurrentDeptEmp record, @Param("example") CurrentDeptEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table current_dept_emp
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CurrentDeptEmp record, @Param("example") CurrentDeptEmpExample example);
}