package com.codejoys.company.mapper;

import com.codejoys.company.entity.Departments;
import com.codejoys.company.entity.DepartmentsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DepartmentsMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated
     */
    long countByExample(DepartmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated
     */
    int deleteByExample(DepartmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String deptNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated
     */
    int insert(Departments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated
     */
    int insertSelective(Departments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated
     */
    List<Departments> selectByExample(DepartmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated
     */
    Departments selectByPrimaryKey(String deptNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Departments record, @Param("example") DepartmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Departments record, @Param("example") DepartmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Departments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Departments record);
}