package com.codejoys.company.mapper;

import com.codejoys.company.entity.DeptManager;
import com.codejoys.company.entity.DeptManagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeptManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated
     */
    long countByExample(DeptManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated
     */
    int deleteByExample(DeptManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("empNo") Integer empNo, @Param("deptNo") String deptNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated
     */
    int insert(DeptManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated
     */
    int insertSelective(DeptManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated
     */
    List<DeptManager> selectByExample(DeptManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated
     */
    DeptManager selectByPrimaryKey(@Param("empNo") Integer empNo, @Param("deptNo") String deptNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DeptManager record, @Param("example") DeptManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DeptManager record, @Param("example") DeptManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DeptManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DeptManager record);
}