package com.codejoys.company.mapper;

import com.codejoys.company.entity.ViewEmpTitle;
import com.codejoys.company.entity.ViewEmpTitleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ViewEmpTitleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_emp_title
     *
     * @mbg.generated
     */
    long countByExample(ViewEmpTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_emp_title
     *
     * @mbg.generated
     */
    int deleteByExample(ViewEmpTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_emp_title
     *
     * @mbg.generated
     */
    int insert(ViewEmpTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_emp_title
     *
     * @mbg.generated
     */
    int insertSelective(ViewEmpTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_emp_title
     *
     * @mbg.generated
     */
    List<ViewEmpTitle> selectByExample(ViewEmpTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_emp_title
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ViewEmpTitle record, @Param("example") ViewEmpTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_emp_title
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ViewEmpTitle record, @Param("example") ViewEmpTitleExample example);
}