package com.codejoys.company.mapper;

import com.codejoys.company.entity.Vv;
import com.codejoys.company.entity.VvExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VvMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vv
     *
     * @mbg.generated
     */
    long countByExample(VvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vv
     *
     * @mbg.generated
     */
    int deleteByExample(VvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vv
     *
     * @mbg.generated
     */
    int insert(Vv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vv
     *
     * @mbg.generated
     */
    int insertSelective(Vv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vv
     *
     * @mbg.generated
     */
    List<Vv> selectByExample(VvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vv
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Vv record, @Param("example") VvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vv
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Vv record, @Param("example") VvExample example);
}