package com.codejoys.company.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table current_dept_emp
 */
public class CurrentDeptEmp implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column current_dept_emp.emp_no
     *
     * @mbg.generated
     */
    private Integer empNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column current_dept_emp.dept_no
     *
     * @mbg.generated
     */
    private String deptNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column current_dept_emp.from_date
     *
     * @mbg.generated
     */
    private Date fromDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column current_dept_emp.to_date
     *
     * @mbg.generated
     */
    private Date toDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table current_dept_emp
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column current_dept_emp.emp_no
     *
     * @return the value of current_dept_emp.emp_no
     *
     * @mbg.generated
     */
    public Integer getEmpNo() {
        return empNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column current_dept_emp.emp_no
     *
     * @param empNo the value for current_dept_emp.emp_no
     *
     * @mbg.generated
     */
    public void setEmpNo(Integer empNo) {
        this.empNo = empNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column current_dept_emp.dept_no
     *
     * @return the value of current_dept_emp.dept_no
     *
     * @mbg.generated
     */
    public String getDeptNo() {
        return deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column current_dept_emp.dept_no
     *
     * @param deptNo the value for current_dept_emp.dept_no
     *
     * @mbg.generated
     */
    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column current_dept_emp.from_date
     *
     * @return the value of current_dept_emp.from_date
     *
     * @mbg.generated
     */
    public Date getFromDate() {
        return fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column current_dept_emp.from_date
     *
     * @param fromDate the value for current_dept_emp.from_date
     *
     * @mbg.generated
     */
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column current_dept_emp.to_date
     *
     * @return the value of current_dept_emp.to_date
     *
     * @mbg.generated
     */
    public Date getToDate() {
        return toDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column current_dept_emp.to_date
     *
     * @param toDate the value for current_dept_emp.to_date
     *
     * @mbg.generated
     */
    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table current_dept_emp
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", empNo=").append(empNo);
        sb.append(", deptNo=").append(deptNo);
        sb.append(", fromDate=").append(fromDate);
        sb.append(", toDate=").append(toDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}