package io.gitee.raochenglengwen.entity;

import java.io.Serializable;

public class Sc implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc.sid
     *
     * @mbg.generated Wed Aug 21 20:25:49 CST 2019
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc.cid
     *
     * @mbg.generated Wed Aug 21 20:25:49 CST 2019
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc.score
     *
     * @mbg.generated Wed Aug 21 20:25:49 CST 2019
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc
     *
     * @mbg.generated Wed Aug 21 20:25:49 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc.sid
     *
     * @return the value of sc.sid
     *
     * @mbg.generated Wed Aug 21 20:25:49 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc.sid
     *
     * @param sid the value for sc.sid
     *
     * @mbg.generated Wed Aug 21 20:25:49 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc.cid
     *
     * @return the value of sc.cid
     *
     * @mbg.generated Wed Aug 21 20:25:49 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc.cid
     *
     * @param cid the value for sc.cid
     *
     * @mbg.generated Wed Aug 21 20:25:49 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc.score
     *
     * @return the value of sc.score
     *
     * @mbg.generated Wed Aug 21 20:25:49 CST 2019
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc.score
     *
     * @param score the value for sc.score
     *
     * @mbg.generated Wed Aug 21 20:25:49 CST 2019
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbg.generated Wed Aug 21 20:25:49 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sid=").append(sid);
        sb.append(", cid=").append(cid);
        sb.append(", score=").append(score);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}